// SPDX-FileCopyrightText: 2026 Paweł Krzywdziński and Contributors
// SPDX-License-Identifier: Apache-2.0

/// Every family of cases, one for each contract the library declares: the controls, the parts of an application's
/// structure, then the tiers.
/// Design: docs/design/host/conformance.md#one-family-per-contract
@_spi(Host) public enum Families {
    /// Every family, section by section as the dictionary has them.
    public static let all: [any ConformanceFamily.Type] = [
        ActivityIndicatorTests.self,
        ButtonTests.self,
        CanvasTests.self,
        CheckBoxTests.self,
        ColorBoxTests.self,
        DatePickerTests.self,
        EllipseTests.self,
        GridTests.self,
        HStackTests.self,
        ImageTests.self,
        TextTests.self,
        LineTests.self,
        MapTests.self,
        PathTests.self,
        PickerTests.self,
        PolygonTests.self,
        PolylineTests.self,
        ProgressBarTests.self,
        RadioButtonTests.self,
        RectangleTests.self,
        ScrollViewTests.self,
        ItemsViewTests.self,
        SearchFieldTests.self,
        SliderTests.self,
        StepperTests.self,
        SwitchTests.self,
        TextEditorTests.self,
        TextFieldTests.self,
        TimePickerTests.self,
        VStackTests.self,
        WebViewTests.self,
        ZStackTests.self,
        ApplicationTests.self,
        ContextMenuTests.self,
        MenuTests.self,
        MenuBarTests.self,
        MenuItemTests.self,
        DividerTests.self,
        ModalStackTests.self,
        NavigationStackTests.self,
        OverlayTests.self,
        PageTests.self,
        MarkerTests.self,
        SceneTests.self,
        TextSpanTests.self,
        TextSpansTests.self,
        SplitViewTests.self,
        TabViewTests.self,
        TitleViewTests.self,
        ToolbarItemTests.self,
        ToolbarItemGroupTests.self,
        WindowTests.self,
        PropertyContainerTests.self,
        VisualElementTests.self,
        ViewTests.self,
        LayoutTests.self,
        StackTests.self,
        TextInputTests.self,
        ShapeTests.self,
        TextualElementTests.self,
        TextStyleElementTests.self,
        FontElementTests.self,
        TextAlignmentElementTests.self,
        LineHeightElementTests.self,
        DecorableTextElementTests.self,
        PaddingElementTests.self,
        BorderElementTests.self,
        ImageElementTests.self,
        TintElementTests.self,
        BarElementTests.self,
        MenuItemElementTests.self,
        PageElementTests.self,
    ]
}
