// SPDX-FileCopyrightText: 2026 Paweł Krzywdziński and Contributors
// SPDX-License-Identifier: Apache-2.0

import XCTest
@_spi(Host) @testable import StateUI

/// The C boundary exported for foreign-language native hosts, and the MAUI
/// host's side of it.
///
/// Nothing at run time enforces that the two sides name the same functions: a
/// renamed entry point, an export with no import or an import with no export
/// all build cleanly on both sides and fail on a device, as
/// `EntryPointNotFoundException` or a function nobody calls. So it is read out
/// of the sources here - a regex over source code is acceptable in a TEST,
/// where it can only under-report, and never in anything the library runs.
final class BridgeTests: XCTestCase {
    /// `Bridge/Exports.swift`, the one place `@_cdecl` is allowed.
    private func exports() throws -> String {
        try String(
            contentsOf: Fixtures.sources
                .appendingPathComponent("Bridge")
                .appendingPathComponent("Exports.swift"),
            encoding: .utf8)
    }

    /// `lib/StateUI.Maui/Sources/Interop/CoreLink.cs`, the other side.
    private func imports() throws -> String {
        try String(
            contentsOf: Fixtures.repository
                .appendingPathComponent("lib/StateUI.Maui/Sources/Interop/CoreLink.cs"),
            encoding: .utf8)
    }

    /// `.scripts/Maui/build-windows.ps1`, whose scan writes the Windows export list.
    private func windowsScript() throws -> String {
        try String(
            contentsOf: Fixtures.repository.appendingPathComponent(".scripts/Maui/build-windows.ps1"),
            encoding: .utf8)
    }

    /// Every exported entry point has one unambiguous name.
    func testEveryExportNameIsUnique() throws {
        let names = try exports().occurrences(between: "@_cdecl(\"", and: "\")")

        XCTAssertFalse(names.isEmpty, "no exports found - the scan is broken")
        XCTAssertEqual(Set(names).count, names.count, "two exports carry the same C name")
    }

    /// Every function exported to .NET has an import, and nothing is imported
    /// that is not exported. `stateui_app_register` is deliberately absent
    /// from both: it lives in the APPLICATION's module and its import is
    /// generated by `StateUI.targets`, because this library cannot name an
    /// application.
    func testEveryExportHasItsImportAndNothingElse() throws {
        let exported = Set(try exports().occurrences(between: "@_cdecl(\"", and: "\")"))
        let imported = Set(try imports().occurrences(between: "EntryPoint = \"", and: "\""))

        XCTAssertFalse(exported.isEmpty, "no exports found - the scan is broken")

        XCTAssertEqual(
            exported.subtracting(imported), [],
            "exported from Swift with no P/Invoke in CoreLink.cs")

        XCTAssertEqual(
            imported.subtracting(exported), [],
            "imported in CoreLink.cs with no @_cdecl behind it - "
                + "EntryPointNotFoundException at first call")
    }

    /// Both sides take the same number of arguments, function by function. A
    /// count is as far as text can honestly go, and it already catches the
    /// silent failure: an argument added on one side reads garbage on the
    /// other rather than failing to bind.
    func testEveryExportAgreesWithItsImportOnArity() throws {
        func arity(of parameters: String) -> Int {
            let trimmed = parameters.trimmingCharacters(in: .whitespacesAndNewlines)
            return trimmed.isEmpty ? 0 : trimmed.filter { $0 == "," }.count + 1
        }

        var exported: [String: Int] = [:]
        for piece in try exports().components(separatedBy: "@_cdecl(\"").dropFirst() {
            guard let name = piece.occurrences(between: "", and: "\")").first,
                  let signature = piece.occurrences(between: "func ", and: ")").first,
                  let open = signature.firstIndex(of: "(")
            else { continue }

            exported[name] = arity(of: String(signature[signature.index(after: open)...]))
        }

        var imported: [String: Int] = [:]
        for piece in try imports().components(separatedBy: "EntryPoint = \"").dropFirst() {
            guard let name = piece.occurrences(between: "", and: "\"").first,
                  let declaration = piece.occurrences(between: "partial ", and: ";").first,
                  let open = declaration.firstIndex(of: "("),
                  let close = declaration.lastIndex(of: ")")
            else { continue }

            imported[name] = arity(of: String(declaration[declaration.index(after: open)..<close]))
        }

        for (name, count) in exported.sorted(by: { $0.key < $1.key }) {
            XCTAssertEqual(
                imported[name], count,
                "\(name) takes \(count) argument(s) in Swift and "
                    + "\(imported[name].map(String.init) ?? "none") in C#")
        }
    }

    /// Every export is spelled the way the Windows build's scan reads it: the
    /// script greps the sources for `@_cdecl("…")` to write the `.def` export
    /// list, and a spelling it misses builds a DLL that fails at first call on
    /// the one platform nothing here runs on.
    func testEveryExportIsSpelledTheWayTheWindowsScanReads() throws {
        guard let pattern = try windowsScript().occurrences(between: "-Pattern '", and: "'").first else {
            return XCTFail("build-windows.ps1 no longer scans with -Pattern '…'")
        }

        let scan = try NSRegularExpression(pattern: pattern)

        for line in try exports().components(separatedBy: "\n") where line.contains("cdecl(\"") {
            let range = NSRange(line.startIndex..., in: line)

            XCTAssertNotNil(
                scan.firstMatch(in: line, range: range),
                "the Windows .def scan (\(pattern)) would miss: \(line.trimmingCharacters(in: .whitespaces))")
        }
    }

    /// Every `@_cdecl` in the library is in `Bridge/Exports.swift`.
    func testEveryExportLivesInTheBridgeFile() throws {
        for (path, text) in try Fixtures.allSources()
        where !path.hasSuffix("Bridge/Exports.swift") {
            let code = text.split(separator: "\n", omittingEmptySubsequences: false)
                .map { $0.drop(while: { $0 == " " }) }
                .filter { !$0.hasPrefix("//") }
                .joined(separator: "\n")

            XCTAssertFalse(
                code.contains("@_cdecl(\""),
                "\(path) declares an export; they all belong in Bridge/Exports.swift")
        }
    }

    /// The Windows `.def` scan drops comment lines, the way the guards do: the
    /// library documents `stateUIUseApp` by showing an application the one
    /// line it writes, and a scan that reads that exports a name nothing in
    /// the library defines - `lld-link` then produces no DLL at all.
    func testTheWindowsExportScanReadsNoProse() throws {
        let script = try windowsScript()

        guard let scan = script.range(of: "-Pattern '") else {
            return XCTFail("build-windows.ps1 no longer scans with -Pattern '…'")
        }

        let pipeline = script[..<scan.lowerBound].suffix(400)

        XCTAssertTrue(
            pipeline.contains("StartsWith(\"//\")"),
            "build-windows.ps1 scans the sources for @_cdecl without dropping comment lines first:\n\n\(pipeline)")
    }

    /// And what the scan finds, comments dropped, is exactly what the library
    /// declares - so a stray export is caught here as well as a missing one.
    func testTheWindowsExportScanFindsExactlyWhatIsDeclared() throws {
        let declared = Set(try exports()
            .components(separatedBy: "\n")
            .filter { !$0.trimmingCharacters(in: .whitespaces).hasPrefix("//") }
            .flatMap { $0.occurrences(between: "@_cdecl(\"", and: "\"") })

        var found: Set<String> = []

        for (_, text) in try Fixtures.allSources() {
            found.formUnion(text
                .components(separatedBy: "\n")
                .filter { !$0.trimmingCharacters(in: .whitespaces).hasPrefix("//") }
                .flatMap { $0.occurrences(between: "@_cdecl(\"", and: "\"") })
        }

        XCTAssertEqual(found.sorted(), declared.sorted())
    }

    /// The environment a host pushes before the first render is readable while
    /// the tree is built.
    func testTheEnvironmentTheHostPushesIsReadableAtBuildTime() {
        defer {
            StandardEnvironment.device.formFactor = .unknown
            Renderer.shared.clearInvalidation()
        }

        XCTAssertEqual(StandardEnvironment.device.formFactor, .unknown)

        var out: [UInt8] = []
        out.u8(Wire.version)
        out.u8(5)
        out.u8(7)
        for value in [
            PropValue.enumeration(FormFactor.desktop.rawValue), .string("macOS"),
            .string(""), .string(""), .string(""), .string(""),
            .enumeration(DeviceType.physical.rawValue),
        ] {
            out.value(value)
        }

        let applied = out.withUnsafeBufferPointer {
            stateui_set_environment($0.baseAddress, Int32($0.count))
        }

        XCTAssertEqual(applied, 1)
        XCTAssertEqual(StandardEnvironment.device.formFactor, .desktop)
    }
}
