// SPDX-FileCopyrightText: 2026 Paweł Krzywdziński and Contributors
// SPDX-License-Identifier: Apache-2.0

/// What this host realizes, member by member - the AppKit column of the
/// control dictionary, `docs/controls/`.
///
/// A record names an entry of the dictionary - a control, or a part of an
/// application's structure - or a tier, the protocol an entry takes the member
/// from; an entry's own record wins over its tier's. A member is recorded once
/// this host realizes it and a test of this package covers it; `.partial` says
/// what is still missing. `AppKitRealizationTests` holds the dictionary's
/// AppKit column equal to these records, and
/// `python3 .scripts/controls-dictionary.py` writes the column from them.
enum AppKitRealization {
    /// Realized in full.
    case complete(_ owner: String, _ member: String)

    /// Realized, but incomplete - `missing` says what is not.
    case partial(_ owner: String, _ member: String, missing: String)

    /// The entry or tier the record is about.
    var owner: String {
        switch self {
        case .complete(let owner, _), .partial(let owner, _, _):
            return owner
        }
    }

    /// The member the record is about - a property, or a handler's event.
    var member: String {
        switch self {
        case .complete(_, let member), .partial(_, let member, _):
            return member
        }
    }

    /// The entries this host shows as unsupported, `AppKitUnsupportedView`:
    /// none of their members is realized.
    static let unrealized: Set<String> = ["Map", "PositionIndicator", "RefreshView", "SwipeView", "WebView"]

    /// The entries this host presents with no view of their own - a title
    /// bar is the window's - so no tier's record reaches them: only a member
    /// the entry's own records name is realized.
    static let viewless: Set<String> = ["TitleBar"]

    /// Every record, the tiers' first.
    static let records: [AppKitRealization] = [
        // MARK: Tiers - a member every wearer realizes alike
        .complete("BarElement", "barBackgroundColor"),
        .complete("DecorableTextElement", "textDecorations"),
        .complete("InputView", "cursorPosition"),
        .complete("InputView", "isReadOnly"),
        .complete("InputView", "isSpellCheckEnabled"),
        .complete("InputView", "isTextPredictionEnabled"),
        .complete("InputView", "maximumLength"),
        .complete("InputView", "placeholder"),
        .complete("InputView", "placeholderColor"),
        .complete("InputView", "selectionLength"),
        .complete("InputView", "textChanged"),
        .complete("Layout", "letsInputThrough"),
        .complete("LineHeightElement", "lineHeight"),
        .complete("MenuItemElement", "clicked"),
        .complete("MenuItemElement", "icon"),
        .complete("MenuItemElement", "isEnabled"),
        .complete("MenuItemElement", "text"),
        .complete("PageElement", "icon"),
        .complete("PageElement", "title"),
        .complete("Shape", "fill"),
        .partial("Shape", "stroke", missing: "AppKit strokes with a colour; a gradient brush draws no outline."),
        .complete("Shape", "strokeDashOffset"),
        .complete("Shape", "strokeDashPattern"),
        .complete("Shape", "strokeLineCap"),
        .complete("Shape", "strokeLineJoin"),
        .complete("Shape", "strokeMiterLimit"),
        .complete("Shape", "strokeWidth"),
        .complete("StackBase", "spacing"),
        .complete("TextElement", "text"),
        .complete("View", "absoluteLayoutBounds"),
        .complete("View", "absoluteLayoutProportions"),
        .complete("View", "frameChanged"),
        .complete("View", "gridColumn"),
        .complete("View", "gridColumnSpan"),
        .complete("View", "gridRow"),
        .complete("View", "gridRowSpan"),
        .complete("View", "horizontalAlignment"),
        .complete("View", "margin"),
        .partial("View", "panTouchCount", missing: "AppKit recognises a one-finger pan only; any other `panTouchCount` turns the pan off."),
        .complete("View", "panUpdated"),
        .complete("View", "pinchUpdated"),
        .complete("View", "pointerEntered"),
        .complete("View", "pointerExited"),
        .complete("View", "pointerMoved"),
        .complete("View", "pointerPressed"),
        .complete("View", "pointerReleased"),
        .complete("View", "swipeDirection"),
        .complete("View", "swipeThreshold"),
        .complete("View", "swiped"),
        .complete("View", "tapCount"),
        .complete("View", "tapped"),
        .complete("View", "verticalAlignment"),
        .complete("VisualElement", "accessibilityHeadingLevel"),
        .complete("VisualElement", "accessibilityHint"),
        .complete("VisualElement", "accessibilityLabel"),
        .complete("VisualElement", "automationExcludedWithChildren"),
        .complete("VisualElement", "frame"),
        .complete("VisualElement", "height"),
        .complete("VisualElement", "isAccessibilityHidden"),
        .complete("VisualElement", "isFocusedChanged"),
        .complete("VisualElement", "isVisible"),
        .complete("VisualElement", "maximumHeight"),
        .complete("VisualElement", "maximumWidth"),
        .complete("VisualElement", "minimumHeight"),
        .complete("VisualElement", "minimumWidth"),
        .complete("VisualElement", "opacity"),
        .complete("VisualElement", "pivotX"),
        .complete("VisualElement", "pivotY"),
        .complete("VisualElement", "rotation"),
        .complete("VisualElement", "rotationX"),
        .complete("VisualElement", "rotationY"),
        .complete("VisualElement", "scale"),
        .complete("VisualElement", "scaleX"),
        .complete("VisualElement", "scaleY"),
        .complete("VisualElement", "translationX"),
        .complete("VisualElement", "translationY"),
        .complete("VisualElement", "width"),

        // MARK: Entries - a control's or a part's own, and where it differs from its tier
        .complete("AbsoluteLayout", "accessibilityIdentifier"),
        .partial("AbsoluteLayout", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("AbsoluteLayout", "ignoresInput"),
        .complete("ActivityIndicator", "accessibilityIdentifier"),
        .partial("ActivityIndicator", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("ActivityIndicator", "isRunning"),
        .complete("Border", "accessibilityIdentifier"),
        .complete("Border", "background"),
        .complete("Border", "ignoresInput"),
        .complete("Border", "padding"),
        .complete("Border", "shape"),
        .partial("Border", "stroke", missing: "AppKit strokes with a colour; a gradient brush draws no outline."),
        .complete("Border", "strokeWidth"),
        .complete("Button", "accessibilityIdentifier"),
        .partial("Button", "aspect", missing: "AppKit's button has no covering scale: `.fill` fits the icon, as `.fit` does."),
        .partial("Button", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Button", "borderColor"),
        .complete("Button", "borderWidth"),
        .complete("Button", "clicked"),
        .complete("Button", "cornerRadius"),
        .complete("Button", "fontAttributes"),
        .complete("Button", "fontFamily"),
        .complete("Button", "fontSize"),
        .complete("Button", "icon"),
        .complete("Button", "iconPosition"),
        .complete("Button", "isEnabled"),
        .complete("Button", "lineBreak"),
        .complete("Button", "padding"),
        .complete("Button", "pressed"),
        .complete("Button", "released"),
        .complete("Button", "textColor"),
        .complete("Canvas", "accessibilityIdentifier"),
        .partial("Canvas", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Canvas", "drawable"),
        .complete("Canvas", "ignoresInput"),
        .complete("CheckBox", "accessibilityIdentifier"),
        .partial("CheckBox", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("CheckBox", "isEnabled"),
        .complete("CheckBox", "isOn"),
        .complete("CheckBox", "tint"),
        .complete("CheckBox", "toggled"),
        .complete("ColorBox", "accessibilityIdentifier"),
        .partial("ColorBox", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("ColorBox", "color"),
        .complete("ColorBox", "cornerRadius"),
        .complete("ColorBox", "ignoresInput"),
        .complete("DatePicker", "accessibilityIdentifier"),
        .partial("DatePicker", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("DatePicker", "date"),
        .complete("DatePicker", "dateChanged"),
        .complete("DatePicker", "fontAttributes"),
        .complete("DatePicker", "fontFamily"),
        .complete("DatePicker", "fontSize"),
        .complete("DatePicker", "isEnabled"),
        .complete("DatePicker", "maximumDate"),
        .complete("DatePicker", "minimumDate"),
        .complete("DatePicker", "textColor"),
        .complete("Ellipse", "accessibilityIdentifier"),
        .partial("Ellipse", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Ellipse", "ignoresInput"),
        .complete("Grid", "accessibilityIdentifier"),
        .partial("Grid", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Grid", "columnSpacing"),
        .complete("Grid", "columns"),
        .complete("Grid", "ignoresInput"),
        .complete("Grid", "padding"),
        .complete("Grid", "rowSpacing"),
        .complete("Grid", "rows"),
        .complete("HStack", "accessibilityIdentifier"),
        .partial("HStack", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("HStack", "ignoresInput"),
        .complete("HStack", "padding"),
        .complete("Image", "accessibilityIdentifier"),
        .complete("Image", "aspect"),
        .partial("Image", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Image", "ignoresInput"),
        .complete("Image", "isAnimating"),
        .complete("Label", "accessibilityIdentifier"),
        .partial("Label", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Label", "characterSpacing"),
        .complete("Label", "fontAttributes"),
        .complete("Label", "fontFamily"),
        .complete("Label", "fontSize"),
        .complete("Label", "horizontalTextAlignment"),
        .complete("Label", "ignoresInput"),
        .complete("Label", "lineBreak"),
        .complete("Label", "maximumLines"),
        .complete("Label", "padding"),
        .complete("Label", "textCase"),
        .complete("Label", "textColor"),
        .complete("Label", "verticalTextAlignment"),
        .complete("Line", "accessibilityIdentifier"),
        .complete("Line", "aspect"),
        .partial("Line", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Line", "ignoresInput"),
        .complete("Line", "renderTransform"),
        .complete("Line", "x1"),
        .complete("Line", "x2"),
        .complete("Line", "y1"),
        .complete("Line", "y2"),
        .complete("Menu", "isEnabled"),
        .partial("MenuItem", "accessibilityIdentifier", missing: "Only an entry of a context menu carries it; an entry the page puts in the menu bar does not."),
        .complete("MenuItem", "isDestructive"),
        .complete("NavigationStack", "accessibilityIdentifier"),
        .complete("NavigationStack", "barForegroundColor"),
        .complete("NavigationStack", "popped"),
        .complete("Page", "appearing"),
        .complete("Page", "backButtonTitle"),
        .complete("Page", "background"),
        .complete("Page", "disappearing"),
        .complete("Page", "hasBackButton"),
        .complete("Page", "hasNavigationBar"),
        .complete("Page", "icon"),
        .complete("Page", "navigatedFrom"),
        .complete("Page", "navigatedTo"),
        .complete("Page", "navigatingFrom"),
        .complete("Page", "padding"),
        .complete("Page", "title"),
        .complete("Path", "accessibilityIdentifier"),
        .complete("Path", "aspect"),
        .partial("Path", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Path", "data"),
        .complete("Path", "ignoresInput"),
        .complete("Path", "renderTransform"),
        .complete("Picker", "accessibilityIdentifier"),
        .partial("Picker", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Picker", "closed"),
        .complete("Picker", "fontAttributes"),
        .complete("Picker", "fontFamily"),
        .complete("Picker", "fontSize"),
        .complete("Picker", "horizontalTextAlignment"),
        .complete("Picker", "isEnabled"),
        .complete("Picker", "isOpen"),
        .complete("Picker", "opened"),
        .complete("Picker", "options"),
        .complete("Picker", "selectedIndex"),
        .complete("Picker", "selectedIndexChanged"),
        .complete("Picker", "textColor"),
        .complete("Picker", "tint"),
        .complete("Picker", "title"),
        .complete("Polygon", "accessibilityIdentifier"),
        .complete("Polygon", "aspect"),
        .partial("Polygon", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Polygon", "fillRule"),
        .complete("Polygon", "ignoresInput"),
        .complete("Polygon", "points"),
        .complete("Polygon", "renderTransform"),
        .complete("Polyline", "accessibilityIdentifier"),
        .complete("Polyline", "aspect"),
        .partial("Polyline", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Polyline", "fillRule"),
        .complete("Polyline", "ignoresInput"),
        .complete("Polyline", "points"),
        .complete("Polyline", "renderTransform"),
        .complete("ProgressBar", "accessibilityIdentifier"),
        .partial("ProgressBar", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("ProgressBar", "progress"),
        .complete("RadioButton", "accessibilityIdentifier"),
        .partial("RadioButton", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("RadioButton", "fontAttributes"),
        .complete("RadioButton", "fontFamily"),
        .complete("RadioButton", "fontSize"),
        .complete("RadioButton", "groupName"),
        .complete("RadioButton", "isEnabled"),
        .complete("RadioButton", "isOn"),
        .complete("RadioButton", "padding"),
        .complete("RadioButton", "textCase"),
        .complete("RadioButton", "textColor"),
        .complete("RadioButton", "toggled"),
        .complete("Rectangle", "accessibilityIdentifier"),
        .partial("Rectangle", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Rectangle", "cornerRadius"),
        .complete("Rectangle", "ignoresInput"),
        .complete("Scene", "activated"),
        .complete("Scene", "deactivated"),
        .complete("Scene", "destroying"),
        .complete("Scene", "stopped"),
        .complete("Scene", "windowClosed"),
        .complete("Scene", "windowRestored"),
        .complete("ScrollView", "accessibilityIdentifier"),
        .partial("ScrollView", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("ScrollView", "horizontalScrollBarVisibility"),
        .complete("ScrollView", "orientation"),
        .complete("ScrollView", "padding"),
        .complete("ScrollView", "scrollStopped"),
        .complete("ScrollView", "verticalScrollBarVisibility"),
        .complete("SearchField", "accessibilityIdentifier"),
        .partial("SearchField", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("SearchField", "fontAttributes"),
        .complete("SearchField", "fontFamily"),
        .complete("SearchField", "fontSize"),
        .complete("SearchField", "horizontalTextAlignment"),
        .complete("SearchField", "isEnabled"),
        .complete("SearchField", "submitted"),
        .complete("SearchField", "textColor"),
        .complete("Slider", "accessibilityIdentifier"),
        .partial("Slider", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Slider", "dragCompleted"),
        .complete("Slider", "dragStarted"),
        .complete("Slider", "isEnabled"),
        .complete("Slider", "maximum"),
        .complete("Slider", "minimum"),
        .complete("Slider", "tint"),
        .complete("Slider", "value"),
        .complete("Slider", "valueChanged"),
        .complete("SplitView", "accessibilityIdentifier"),
        .complete("SplitView", "isSidebarVisibleChanged"),
        .complete("Stepper", "accessibilityIdentifier"),
        .partial("Stepper", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Stepper", "isEnabled"),
        .complete("Stepper", "maximum"),
        .complete("Stepper", "minimum"),
        .complete("Stepper", "step"),
        .complete("Stepper", "value"),
        .complete("Stepper", "valueChanged"),
        .complete("Switch", "accessibilityIdentifier"),
        .partial("Switch", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Switch", "isEnabled"),
        .complete("Switch", "isOn"),
        .complete("Switch", "toggled"),
        .complete("TabbedView", "accessibilityIdentifier"),
        .complete("TabbedView", "currentPage"),
        .complete("TabbedView", "currentPageChanged"),
        .complete("TextEditor", "accessibilityIdentifier"),
        .partial("TextEditor", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("TextEditor", "fontAttributes"),
        .complete("TextEditor", "fontFamily"),
        .complete("TextEditor", "fontSize"),
        .complete("TextEditor", "growsWithText"),
        .complete("TextEditor", "horizontalTextAlignment"),
        .complete("TextEditor", "isEnabled"),
        .complete("TextEditor", "textColor"),
        .complete("TextField", "accessibilityIdentifier"),
        .partial("TextField", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("TextField", "fontAttributes"),
        .complete("TextField", "fontFamily"),
        .complete("TextField", "fontSize"),
        .complete("TextField", "horizontalTextAlignment"),
        .complete("TextField", "isEnabled"),
        .complete("TextField", "isPassword"),
        .complete("TextField", "submitted"),
        .complete("TextField", "textColor"),
        .complete("TimePicker", "accessibilityIdentifier"),
        .partial("TimePicker", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("TimePicker", "fontAttributes"),
        .complete("TimePicker", "fontFamily"),
        .complete("TimePicker", "fontSize"),
        .complete("TimePicker", "isEnabled"),
        .complete("TimePicker", "textColor"),
        .complete("TimePicker", "time"),
        .complete("TimePicker", "timeChanged"),
        .partial("TitleBar", "background", missing: "AppKit paints a colour on the window's bar band; a brush is drawn only by `Border`."),
        .complete("TitleBar", "barForegroundColor"),
        .complete("TitleBar", "icon"),
        .complete("TitleBar", "subtitle"),
        .complete("ToolbarItem", "placement"),
        .complete("ToolbarItem", "priority"),
        .complete("VStack", "accessibilityIdentifier"),
        .partial("VStack", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("VStack", "ignoresInput"),
        .complete("VStack", "padding"),
        .complete("Window", "activated"),
        .complete("Window", "created"),
        .complete("Window", "deactivated"),
        .complete("Window", "destroying"),
        .complete("Window", "floatsOnTop"),
        .complete("Window", "height"),
        .complete("Window", "hidesWhenInactive"),
        .complete("Window", "isMaximizable"),
        .complete("Window", "isMinimizable"),
        .complete("Window", "isTranslucent"),
        .complete("Window", "maximumHeight"),
        .complete("Window", "maximumWidth"),
        .complete("Window", "minimumHeight"),
        .complete("Window", "minimumWidth"),
        .complete("Window", "modalPopped"),
        .complete("Window", "resumed"),
        .complete("Window", "stopped"),
        .complete("Window", "title"),
        .complete("Window", "width"),
        .complete("Window", "windowType"),
        .complete("Window", "windowValue"),
        .complete("Window", "x"),
        .complete("Window", "y"),
    ]
}
