// SPDX-FileCopyrightText: 2026 Paweł Krzywdziński and Contributors
// SPDX-License-Identifier: Apache-2.0

/// What this host realizes, member by member - the AppKit column of the
/// control dictionary, `docs/controls/`.
///
/// A record names an entry of the dictionary - a control, or a part of an
/// application's structure - or a tier, the protocol an entry takes the member
/// from; an entry's own record wins over its tier's. A member is recorded once
/// this host realizes it and a test of this package covers it; `.partial` says
/// what is still missing; an act is recorded where a test of this package
/// performs it. `ControlDictionaryTests`, in the core's suite, reads these
/// records, holds each to the contracts, and renders the dictionary's AppKit
/// column from them.
enum AppKitRealization {
    /// Realized in full.
    case complete(_ owner: String, _ member: String)

    /// Realized, but incomplete - `missing` says what is not.
    case partial(_ owner: String, _ member: String, missing: String)

    /// The entry or tier the record is about.
    var owner: String {
        switch self {
        case .complete(let owner, _), .partial(let owner, _, _):
            return owner
        }
    }

    /// The member the record is about - a property, or a handler's event.
    var member: String {
        switch self {
        case .complete(_, let member), .partial(_, let member, _):
            return member
        }
    }

    /// The entries this host realizes none of: those it shows as unsupported,
    /// `AppKitUnsupportedView`, the parts of one, and a style's setters and
    /// visual states, which it has no handling of.
    static let unrealized: Set<String> = [
        "Map", "Pin", "PositionIndicator", "RefreshView", "Setters", "SwipeAction", "SwipeActions", "SwipeView",
        "VisualState", "WebView",
    ]

    /// The entries this host presents with no view of their own - a title
    /// bar is the window's, a span a run of its label's text - so no tier's
    /// record reaches them: only a member the entry's own records name is
    /// realized.
    static let viewless: Set<String> = ["Span", "TitleBar"]

    /// Every record, the tiers' first.
    static let records: [AppKitRealization] = [
        // MARK: Tiers - a member every wearer realizes alike
        .complete("BarElement", "barBackgroundColor"),
        .complete("DecorableTextElement", "textDecorations"),
        .complete("LineHeightElement", "lineHeight"),
        .complete("MenuItemElement", "clicked"),
        .complete("MenuItemElement", "icon"),
        .complete("MenuItemElement", "isEnabled"),
        .complete("MenuItemElement", "text"),
        .complete("PageElement", "icon"),
        .complete("PageElement", "title"),
        .partial("Shape", "stroke", missing: "AppKit strokes with a colour; a gradient brush draws no outline."),
        .partial("View", "panTouchCount", missing: "AppKit recognises a one-finger pan only; any other `panTouchCount` turns the pan off."),

        // MARK: Entries - a control's or a part's own, and where it differs from its tier
        .complete("AbsoluteLayout", "accessibilityIdentifier"),
        .partial("AbsoluteLayout", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("AbsoluteLayout", "ignoresInput"),
        .complete("ActivityIndicator", "accessibilityIdentifier"),
        .partial("ActivityIndicator", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Border", "accessibilityIdentifier"),
        .complete("Border", "background"),
        .complete("Border", "ignoresInput"),
        .complete("Border", "padding"),
        .complete("Border", "shape"),
        .partial("Border", "stroke", missing: "AppKit strokes with a colour; a gradient brush draws no outline."),
        .complete("Border", "strokeWidth"),
        .complete("Button", "accessibilityIdentifier"),
        .partial("Button", "aspect", missing: "AppKit's button has no covering scale: `.fill` fits the icon, as `.fit` does."),
        .partial("Button", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Button", "borderColor"),
        .complete("Button", "borderWidth"),
        .complete("Button", "cornerRadius"),
        .complete("Button", "fontAttributes"),
        .complete("Button", "fontFamily"),
        .complete("Button", "fontSize"),
        .complete("Button", "isEnabled"),
        .complete("Button", "padding"),
        .complete("Button", "textColor"),
        .complete("Canvas", "accessibilityIdentifier"),
        .partial("Canvas", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Canvas", "ignoresInput"),
        .complete("CheckBox", "accessibilityIdentifier"),
        .partial("CheckBox", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("CheckBox", "isEnabled"),
        .complete("CheckBox", "tint"),
        .complete("ColorBox", "accessibilityIdentifier"),
        .partial("ColorBox", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("ColorBox", "ignoresInput"),
        .complete("DatePicker", "accessibilityIdentifier"),
        .partial("DatePicker", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("DatePicker", "fontAttributes"),
        .complete("DatePicker", "fontFamily"),
        .complete("DatePicker", "fontSize"),
        .complete("DatePicker", "isEnabled"),
        .complete("DatePicker", "textColor"),
        .complete("Ellipse", "accessibilityIdentifier"),
        .partial("Ellipse", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Ellipse", "ignoresInput"),
        .complete("Grid", "accessibilityIdentifier"),
        .partial("Grid", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Grid", "ignoresInput"),
        .complete("Grid", "padding"),
        .complete("HStack", "accessibilityIdentifier"),
        .partial("HStack", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("HStack", "ignoresInput"),
        .complete("HStack", "padding"),
        .complete("Image", "accessibilityIdentifier"),
        .complete("Image", "aspect"),
        .partial("Image", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Image", "ignoresInput"),
        .complete("Label", "accessibilityIdentifier"),
        .partial("Label", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Label", "characterSpacing"),
        .complete("Label", "fontAttributes"),
        .complete("Label", "fontFamily"),
        .complete("Label", "fontSize"),
        .complete("Label", "horizontalTextAlignment"),
        .complete("Label", "ignoresInput"),
        .complete("Label", "lineBreak"),
        .complete("Label", "maximumLines"),
        .complete("Label", "padding"),
        .complete("Label", "textCase"),
        .complete("Label", "textColor"),
        .complete("Label", "verticalTextAlignment"),
        .complete("Line", "accessibilityIdentifier"),
        .complete("Line", "aspect"),
        .partial("Line", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Line", "ignoresInput"),
        .complete("Line", "renderTransform"),
        .complete("Menu", "isEnabled"),
        .complete("Menu", "text"),
        .partial("MenuItem", "accessibilityIdentifier", missing: "Only an entry of a context menu carries it; an entry the page puts in the menu bar does not."),
        .complete("MenuItem", "isDestructive"),
        .complete("NavigationStack", "accessibilityIdentifier"),
        .complete("NavigationStack", "barForegroundColor"),
        .complete("NavigationStack", "popped"),
        .complete("Page", "appearing"),
        .complete("Page", "backButtonTitle"),
        .complete("Page", "background"),
        .complete("Page", "disappearing"),
        .complete("Page", "hasBackButton"),
        .complete("Page", "hasNavigationBar"),
        .complete("Page", "icon"),
        .complete("Page", "navigatedFrom"),
        .complete("Page", "navigatedTo"),
        .complete("Page", "navigatingFrom"),
        .complete("Page", "title"),
        .complete("Path", "accessibilityIdentifier"),
        .complete("Path", "aspect"),
        .partial("Path", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Path", "ignoresInput"),
        .complete("Path", "renderTransform"),
        .complete("Picker", "accessibilityIdentifier"),
        .partial("Picker", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Picker", "fontAttributes"),
        .complete("Picker", "fontFamily"),
        .complete("Picker", "fontSize"),
        .complete("Picker", "horizontalTextAlignment"),
        .complete("Picker", "isEnabled"),
        .complete("Picker", "textColor"),
        .complete("Picker", "tint"),
        .complete("Polygon", "accessibilityIdentifier"),
        .complete("Polygon", "aspect"),
        .partial("Polygon", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Polygon", "ignoresInput"),
        .complete("Polygon", "renderTransform"),
        .complete("Polyline", "accessibilityIdentifier"),
        .complete("Polyline", "aspect"),
        .partial("Polyline", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Polyline", "ignoresInput"),
        .complete("Polyline", "renderTransform"),
        .complete("ProgressBar", "accessibilityIdentifier"),
        .partial("ProgressBar", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("RadioButton", "accessibilityIdentifier"),
        .partial("RadioButton", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("RadioButton", "fontAttributes"),
        .complete("RadioButton", "fontFamily"),
        .complete("RadioButton", "fontSize"),
        .complete("RadioButton", "groupName"),
        .complete("RadioButton", "isEnabled"),
        .complete("RadioButton", "padding"),
        .complete("RadioButton", "textCase"),
        .complete("RadioButton", "textColor"),
        .complete("Rectangle", "accessibilityIdentifier"),
        .partial("Rectangle", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Rectangle", "ignoresInput"),
        .complete("Scene", "activated"),
        .complete("Scene", "deactivated"),
        .complete("Scene", "destroying"),
        .complete("Scene", "stopped"),
        .complete("Scene", "windowClosed"),
        .complete("Scene", "windowRestored"),
        .complete("ScrollView", "accessibilityIdentifier"),
        .partial("ScrollView", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("ScrollView", "padding"),
        .complete("ScrollView", "scrollStopped"),
        .complete("ScrollView", "scrollXChanged"),
        .complete("ScrollView", "scrollYChanged"),
        .complete("SearchField", "accessibilityIdentifier"),
        .partial("SearchField", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("SearchField", "fontAttributes"),
        .complete("SearchField", "fontFamily"),
        .complete("SearchField", "fontSize"),
        .complete("SearchField", "horizontalTextAlignment"),
        .complete("SearchField", "isEnabled"),
        .complete("SearchField", "textColor"),
        .complete("Slider", "accessibilityIdentifier"),
        .partial("Slider", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Slider", "isEnabled"),
        .complete("Slider", "tint"),
        .complete("Span", "fontAttributes"),
        .complete("Span", "text"),
        .complete("Span", "textCase"),
        .complete("SplitView", "accessibilityIdentifier"),
        .complete("SplitView", "isSidebarVisibleChanged"),
        .complete("Stepper", "accessibilityIdentifier"),
        .partial("Stepper", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Stepper", "isEnabled"),
        .complete("Switch", "accessibilityIdentifier"),
        .partial("Switch", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("Switch", "isEnabled"),
        .complete("TabbedView", "accessibilityIdentifier"),
        .complete("TabbedView", "currentPage"),
        .complete("TabbedView", "currentPageChanged"),
        .complete("TextEditor", "accessibilityIdentifier"),
        .partial("TextEditor", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("TextEditor", "fontAttributes"),
        .complete("TextEditor", "fontFamily"),
        .complete("TextEditor", "fontSize"),
        .complete("TextEditor", "horizontalTextAlignment"),
        .complete("TextEditor", "isEnabled"),
        .complete("TextEditor", "textColor"),
        .complete("TextField", "accessibilityIdentifier"),
        .partial("TextField", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("TextField", "fontAttributes"),
        .complete("TextField", "fontFamily"),
        .complete("TextField", "fontSize"),
        .complete("TextField", "horizontalTextAlignment"),
        .complete("TextField", "isEnabled"),
        .complete("TextField", "textColor"),
        .complete("TimePicker", "accessibilityIdentifier"),
        .partial("TimePicker", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("TimePicker", "fontAttributes"),
        .complete("TimePicker", "fontFamily"),
        .complete("TimePicker", "fontSize"),
        .complete("TimePicker", "isEnabled"),
        .complete("TimePicker", "textColor"),
        .partial("TitleBar", "background", missing: "AppKit paints a colour on the window's bar band; a brush is drawn only by `Border`."),
        .complete("TitleBar", "barForegroundColor"),
        .complete("TitleBar", "icon"),
        .complete("TitleBar", "subtitle"),
        .complete("TitleBar", "title"),
        .complete("ToolbarItem", "placement"),
        .complete("ToolbarItem", "priority"),
        .complete("VStack", "accessibilityIdentifier"),
        .partial("VStack", "background", missing: "AppKit paints a colour on this view; a brush is drawn only by `Border`."),
        .complete("VStack", "ignoresInput"),
        .complete("VStack", "padding"),
        .complete("Window", "activated"),
        .complete("Window", "created"),
        .complete("Window", "deactivated"),
        .complete("Window", "destroying"),
        .complete("Window", "floatsOnTop"),
        .complete("Window", "height"),
        .complete("Window", "hidesWhenInactive"),
        .complete("Window", "isMaximizable"),
        .complete("Window", "isMinimizable"),
        .complete("Window", "isTranslucent"),
        .complete("Window", "maximumHeight"),
        .complete("Window", "maximumWidth"),
        .complete("Window", "minimumHeight"),
        .complete("Window", "minimumWidth"),
        .complete("Window", "modalPopped"),
        .complete("Window", "resumed"),
        .complete("Window", "stopped"),
        .complete("Window", "title"),
        .complete("Window", "width"),
        .complete("Window", "windowType"),
        .complete("Window", "windowValue"),
        .complete("Window", "x"),
        .complete("Window", "y"),
    ]
}
