// SPDX-FileCopyrightText: 2026 Paweł Krzywdziński and Contributors
// SPDX-License-Identifier: Apache-2.0

namespace StateUI.Maui.Rendering;

/// <summary>
/// What this host realizes, member by member - the MAUI column of the control
/// dictionary, <c>docs/controls/</c>.
/// </summary>
/// <remarks>
/// <para>
/// A record names an entry of the dictionary - a control, or a part of an
/// application's structure - or a tier, the protocol an entry takes the member
/// from; an entry's own record wins over its tier's. A member is recorded once
/// this host realizes it and a test of this host's suite covers it; a partial
/// record says what is still missing.
/// </para>
/// <para>
/// <c>ControlDictionaryTests</c>, in the core's suite, reads these records,
/// holds each to the contracts - a member of the element or tier it names,
/// recorded once, a partial one saying what is missing - and renders the
/// dictionary's MAUI column from them. An act is recorded where a test of this
/// host performs it.
/// </para>
/// </remarks>
internal static class MauiRealization
{
    /// <summary>One member this host realizes.</summary>
    /// <param name="Owner">The entry or tier the record is about.</param>
    /// <param name="Member">The member - a property, or a handler's event.</param>
    /// <param name="Missing">What is not realized yet; null when nothing is.</param>
    internal sealed record Record(string Owner, string Member, string? Missing);

    /// <summary>The entries this host builds nothing for: none of their members is realized.</summary>
    internal static readonly HashSet<string> Unrealized = [];

    /// <summary>Every record, the tiers' first.</summary>
    internal static readonly Record[] Records =
    [
        // Tiers - a member every wearer realizes alike
        Complete("BarElement", "barBackgroundColor"),
        Complete("BorderElement", "borderColor"),
        Complete("BorderElement", "borderWidth"),
        Complete("BorderElement", "cornerRadius"),
        Complete("DecorableTextElement", "textDecorations"),
        Complete("FontElement", "fontAttributes"),
        Complete("FontElement", "fontAutoScalingEnabled"),
        Complete("FontElement", "fontFamily"),
        Complete("FontElement", "fontSize"),
        Complete("InputView", "cursorPosition"),
        Complete("InputView", "inputPurpose"),
        Complete("InputView", "isReadOnly"),
        Complete("InputView", "isSpellCheckEnabled"),
        Complete("InputView", "isTextPredictionEnabled"),
        Complete("InputView", "maximumLength"),
        Complete("InputView", "placeholder"),
        Complete("InputView", "placeholderColor"),
        Complete("InputView", "selectionLength"),
        Complete("InputView", "textChanged"),
        Complete("Layout", "avoidsSafeArea"),
        Complete("Layout", "clipsContent"),
        Complete("Layout", "letsInputThrough"),
        Complete("LineHeightElement", "lineHeight"),
        Complete("MenuItemElement", "clicked"),
        Complete("MenuItemElement", "icon"),
        Complete("MenuItemElement", "isDestructive"),
        Complete("MenuItemElement", "isEnabled"),
        Complete("MenuItemElement", "text"),
        Complete("PaddingElement", "padding"),
        Complete("PageElement", "icon"),
        Complete("PageElement", "title"),
        Complete("Shape", "aspect"),
        Complete("Shape", "fill"),
        Complete("Shape", "renderTransform"),
        Complete("Shape", "stroke"),
        Complete("Shape", "strokeDashOffset"),
        Complete("Shape", "strokeDashPattern"),
        Complete("Shape", "strokeLineCap"),
        Complete("Shape", "strokeLineJoin"),
        Complete("Shape", "strokeMiterLimit"),
        Complete("Shape", "strokeWidth"),
        Complete("StackBase", "spacing"),
        Complete("TextAlignmentElement", "horizontalTextAlignment"),
        Complete("TextAlignmentElement", "verticalTextAlignment"),
        Complete("TextElement", "text"),
        Complete("TextElement", "textCase"),
        Complete("TextStyleElement", "characterSpacing"),
        Complete("TextStyleElement", "textColor"),
        Complete("TintElement", "tint"),
        Complete("View", "absoluteLayoutBounds"),
        Complete("View", "absoluteLayoutProportions"),
        Complete("View", "allowDrop"),
        Complete("View", "canDrag"),
        Complete("View", "dragLeave"),
        Complete("View", "dragOver"),
        Complete("View", "dragStarting"),
        Complete("View", "dragText"),
        Complete("View", "drop"),
        Complete("View", "dropCompleted"),
        Complete("View", "frameChanged"),
        Complete("View", "gridColumn"),
        Complete("View", "gridColumnSpan"),
        Complete("View", "gridRow"),
        Complete("View", "gridRowSpan"),
        Complete("View", "horizontalAlignment"),
        Complete("View", "margin"),
        Complete("View", "panTouchCount"),
        Complete("View", "panUpdated"),
        Complete("View", "panXChannel"),
        Complete("View", "panYChannel"),
        Complete("View", "pinchUpdated"),
        Complete("View", "pointerEntered"),
        Complete("View", "pointerExited"),
        Complete("View", "pointerMoved"),
        Complete("View", "pointerPressed"),
        Complete("View", "pointerReleased"),
        Complete("View", "swipeDirection"),
        Complete("View", "swipeThreshold"),
        Complete("View", "swiped"),
        Complete("View", "tapCount"),
        Complete("View", "tapped"),
        Complete("View", "verticalAlignment"),
        Complete("VisualElement", "accessibilityHeadingLevel"),
        Complete("VisualElement", "accessibilityHint"),
        Complete("VisualElement", "accessibilityLabel"),
        Complete("VisualElement", "automationExcludedWithChildren"),
        Complete("VisualElement", "background"),
        Complete("VisualElement", "frame"),
        Complete("VisualElement", "height"),
        Complete("VisualElement", "ignoresInput"),
        Complete("VisualElement", "isAccessibilityHidden"),
        Complete("VisualElement", "isEnabled"),
        Complete("VisualElement", "isFocusedChanged"),
        Complete("VisualElement", "isVisible"),
        Complete("VisualElement", "layoutDirection"),
        Complete("VisualElement", "maximumHeight"),
        Complete("VisualElement", "maximumWidth"),
        Complete("VisualElement", "minimumHeight"),
        Complete("VisualElement", "minimumWidth"),
        Complete("VisualElement", "opacity"),
        Complete("VisualElement", "pivotX"),
        Complete("VisualElement", "pivotY"),
        Complete("VisualElement", "rotation"),
        Complete("VisualElement", "rotationX"),
        Complete("VisualElement", "rotationY"),
        Complete("VisualElement", "scale"),
        Complete("VisualElement", "scaleX"),
        Complete("VisualElement", "scaleY"),
        Complete("VisualElement", "translationX"),
        Complete("VisualElement", "translationY"),
        Complete("VisualElement", "visualStateChanged"),
        Complete("VisualElement", "width"),
        Complete("VisualElement", "zIndex"),

        // Entries - a control's or a part's own, and where it differs from its tier
        Complete("AbsoluteLayout", "accessibilityIdentifier"),
        Complete("ActivityIndicator", "accessibilityIdentifier"),
        Complete("ActivityIndicator", "isRunning"),
        Complete("Application", "currentTime"),
        Complete("Application", "currentTimeZone"),
        Complete("Application", "persistSceneValue"),
        Complete("Application", "persistValue"),
        Complete("Application", "utcOffset"),
        Complete("Border", "accessibilityIdentifier"),
        Complete("Border", "shape"),
        Complete("Border", "stroke"),
        Complete("Border", "strokeDashOffset"),
        Complete("Border", "strokeDashPattern"),
        Complete("Border", "strokeLineCap"),
        Complete("Border", "strokeLineJoin"),
        Complete("Border", "strokeMiterLimit"),
        Complete("Border", "strokeWidth"),
        Complete("Button", "accessibilityIdentifier"),
        Complete("Button", "clicked"),
        Complete("Button", "icon"),
        Complete("Button", "iconPosition"),
        Complete("Button", "iconSpacing"),
        Complete("Button", "lineBreak"),
        Complete("Button", "pressed"),
        Complete("Button", "released"),
        Complete("Canvas", "accessibilityIdentifier"),
        Complete("Canvas", "dragged"),
        Complete("Canvas", "drawable"),
        Complete("Canvas", "pressed"),
        Complete("Canvas", "released"),
        Complete("CheckBox", "accessibilityIdentifier"),
        Complete("CheckBox", "isOn"),
        Complete("CheckBox", "toggled"),
        Complete("ColorBox", "accessibilityIdentifier"),
        Complete("ColorBox", "color"),
        Complete("ColorBox", "cornerRadius"),
        Complete("DatePicker", "accessibilityIdentifier"),
        Complete("DatePicker", "closed"),
        Complete("DatePicker", "date"),
        Complete("DatePicker", "dateChanged"),
        Complete("DatePicker", "format"),
        Complete("DatePicker", "isOpen"),
        Complete("DatePicker", "maximumDate"),
        Complete("DatePicker", "minimumDate"),
        Complete("DatePicker", "opened"),
        Complete("Ellipse", "accessibilityIdentifier"),
        Complete("Grid", "accessibilityIdentifier"),
        Complete("Grid", "columnSpacing"),
        Complete("Grid", "columns"),
        Complete("Grid", "rowSpacing"),
        Complete("Grid", "rows"),
        Complete("HStack", "accessibilityIdentifier"),
        Complete("Image", "accessibilityIdentifier"),
        Complete("Image", "aspect"),
        Complete("Image", "isAnimating"),
        Complete("Image", "source"),
        Complete("Label", "accessibilityIdentifier"),
        Complete("Label", "background"),
        Complete("Label", "lineBreak"),
        Complete("Label", "maximumLines"),
        Complete("Line", "accessibilityIdentifier"),
        Complete("Line", "x1"),
        Complete("Line", "x2"),
        Complete("Line", "y1"),
        Complete("Line", "y2"),
        Complete("Map", "accessibilityIdentifier"),
        Partial("Map", "isScrollEnabled", missing: "Windows and Linux have no map; the Map draws the unknown-control marker there."),
        Partial("Map", "isTrafficEnabled", missing: "Windows and Linux have no map; the Map draws the unknown-control marker there."),
        Partial("Map", "isZoomEnabled", missing: "Windows and Linux have no map; the Map draws the unknown-control marker there."),
        Partial("Map", "mapClicked", missing: "Windows and Linux have no map; the Map draws the unknown-control marker there."),
        Partial("Map", "mapType", missing: "Windows and Linux have no map; the Map draws the unknown-control marker there."),
        Partial("Map", "showsUserLocation", missing: "Windows and Linux have no map; the Map draws the unknown-control marker there."),
        Complete("Menu", "isEnabled"),
        Complete("Menu", "text"),
        Complete("NavigationStack", "barForegroundColor"),
        Complete("NavigationStack", "popped"),
        Complete("Page", "appearing"),
        Complete("Page", "backButtonTitle"),
        Complete("Page", "background"),
        Complete("Page", "disappearing"),
        Complete("Page", "hasBackButton"),
        Complete("Page", "hasNavigationBar"),
        Complete("Page", "icon"),
        Complete("Page", "navigatedFrom"),
        Complete("Page", "navigatedTo"),
        Complete("Page", "navigatingFrom"),
        Complete("Page", "padding"),
        Complete("Page", "title"),
        Complete("Path", "accessibilityIdentifier"),
        Complete("Path", "data"),
        Complete("Picker", "accessibilityIdentifier"),
        Complete("Picker", "closed"),
        Complete("Picker", "isOpen"),
        Complete("Picker", "opened"),
        Complete("Picker", "options"),
        Complete("Picker", "selectedIndex"),
        Complete("Picker", "selectedIndexChanged"),
        Complete("Picker", "title"),
        Partial("Pin", "address", missing: "Windows and Linux have no map; the Map draws the unknown-control marker there."),
        Partial("Pin", "label", missing: "Windows and Linux have no map; the Map draws the unknown-control marker there."),
        Partial("Pin", "location", missing: "Windows and Linux have no map; the Map draws the unknown-control marker there."),
        Partial("Pin", "pinClicked", missing: "Windows and Linux have no map; the Map draws the unknown-control marker there."),
        Partial("Pin", "pinDetailsClicked", missing: "Windows and Linux have no map; the Map draws the unknown-control marker there."),
        Partial("Pin", "type", missing: "Windows and Linux have no map; the Map draws the unknown-control marker there."),
        Complete("Polygon", "accessibilityIdentifier"),
        Complete("Polygon", "fillRule"),
        Complete("Polygon", "points"),
        Complete("Polyline", "accessibilityIdentifier"),
        Complete("Polyline", "fillRule"),
        Complete("Polyline", "points"),
        Complete("PositionIndicator", "accessibilityIdentifier"),
        Complete("PositionIndicator", "count"),
        Complete("PositionIndicator", "hideSingle"),
        Complete("PositionIndicator", "indicatorColor"),
        Complete("PositionIndicator", "indicatorSize"),
        Complete("PositionIndicator", "indicatorsShape"),
        Complete("PositionIndicator", "maximumVisible"),
        Complete("PositionIndicator", "position"),
        Complete("PositionIndicator", "selectedIndicatorColor"),
        Complete("ProgressBar", "accessibilityIdentifier"),
        Complete("ProgressBar", "progress"),
        Complete("RadioButton", "accessibilityIdentifier"),
        Complete("RadioButton", "groupName"),
        Complete("RadioButton", "isOn"),
        Complete("RadioButton", "toggled"),
        Complete("Rectangle", "accessibilityIdentifier"),
        Complete("Rectangle", "cornerRadius"),
        Complete("RefreshView", "accessibilityIdentifier"),
        Complete("RefreshView", "isRefreshEnabled"),
        Complete("RefreshView", "isRefreshing"),
        Complete("RefreshView", "isRefreshingChanged"),
        Complete("RefreshView", "refreshRequested"),
        Complete("Scene", "activated"),
        Complete("Scene", "deactivated"),
        Complete("Scene", "destroying"),
        Complete("Scene", "stopped"),
        Complete("Scene", "windowClosed"),
        Complete("Scene", "windowRestored"),
        Complete("ScrollView", "accessibilityIdentifier"),
        Complete("ScrollView", "horizontalScrollBarVisibility"),
        Complete("ScrollView", "orientation"),
        Complete("ScrollView", "scrollOffset"),
        Complete("ScrollView", "scrollStopped"),
        Complete("ScrollView", "scrollYChanged"),
        Complete("ScrollView", "verticalScrollBarVisibility"),
        Complete("SearchField", "accessibilityIdentifier"),
        Complete("SearchField", "returnKey"),
        Complete("SearchField", "submitted"),
        Complete("Slider", "accessibilityIdentifier"),
        Complete("Slider", "dragCompleted"),
        Complete("Slider", "dragStarted"),
        Complete("Slider", "maximum"),
        Complete("Slider", "minimum"),
        Complete("Slider", "value"),
        Complete("Slider", "valueChanged"),
        Complete("Span", "background"),
        Complete("SplitView", "isSidebarVisible"),
        Complete("SplitView", "isSidebarVisibleChanged"),
        Complete("Stepper", "accessibilityIdentifier"),
        Complete("Stepper", "maximum"),
        Complete("Stepper", "minimum"),
        Complete("Stepper", "step"),
        Complete("Stepper", "value"),
        Complete("Stepper", "valueChanged"),
        Complete("SwipeAction", "background"),
        Complete("SwipeAction", "isVisible"),
        Complete("SwipeActions", "mode"),
        Complete("SwipeActions", "side"),
        Complete("SwipeActions", "swipeBehaviorOnInvoked"),
        Complete("SwipeView", "accessibilityIdentifier"),
        Complete("SwipeView", "swipeChanging"),
        Complete("SwipeView", "swipeEnded"),
        Complete("SwipeView", "swipeStarted"),
        Complete("SwipeView", "threshold"),
        Complete("Switch", "accessibilityIdentifier"),
        Complete("Switch", "isOn"),
        Complete("Switch", "toggled"),
        Complete("TabbedView", "currentPage"),
        Complete("TabbedView", "currentPageChanged"),
        Complete("TextEditor", "accessibilityIdentifier"),
        Complete("TextEditor", "growsWithText"),
        Complete("TextField", "accessibilityIdentifier"),
        Complete("TextField", "isPassword"),
        Complete("TextField", "returnKey"),
        Complete("TextField", "showsClearButton"),
        Complete("TextField", "submitted"),
        Complete("TimePicker", "accessibilityIdentifier"),
        Complete("TimePicker", "closed"),
        Complete("TimePicker", "format"),
        Complete("TimePicker", "isOpen"),
        Complete("TimePicker", "opened"),
        Complete("TimePicker", "time"),
        Complete("TimePicker", "timeChanged"),
        Complete("TitleBar", "accessibilityIdentifier"),
        Complete("TitleBar", "barForegroundColor"),
        Complete("TitleBar", "icon"),
        Complete("TitleBar", "subtitle"),
        Complete("TitleBar", "title"),
        Complete("ToolbarItem", "accessibilityIdentifier"),
        Complete("ToolbarItem", "placement"),
        Complete("ToolbarItem", "priority"),
        Complete("VStack", "accessibilityIdentifier"),
        Complete("VisualState", "group"),
        Complete("VisualState", "name"),
        Complete("WebView", "accessibilityIdentifier"),
        Complete("WebView", "canGoBackChanged"),
        Complete("WebView", "canGoForwardChanged"),
        Complete("WebView", "navigated"),
        Complete("WebView", "navigating"),
        Complete("WebView", "processTerminated"),
        Complete("WebView", "source"),
        Complete("WebView", "userAgent"),
        Complete("Window", "activated"),
        Complete("Window", "created"),
        Complete("Window", "deactivated"),
        Complete("Window", "destroying"),
        Partial("Window", "floatsOnTop", missing: "Only Mac Catalyst keeps the window on top; Windows and Linux leave it among the others."),
        Complete("Window", "height"),
        Complete("Window", "isMaximizable"),
        Complete("Window", "isMinimizable"),
        Complete("Window", "maximumHeight"),
        Complete("Window", "maximumWidth"),
        Complete("Window", "minimumHeight"),
        Complete("Window", "minimumWidth"),
        Complete("Window", "modalPopped"),
        Complete("Window", "resumed"),
        Complete("Window", "stopped"),
        Complete("Window", "title"),
        Complete("Window", "width"),
        Complete("Window", "windowType"),
        Complete("Window", "windowValue"),
        Complete("Window", "x"),
        Complete("Window", "y"),
    ];

    /// <summary>A member realized in full.</summary>
    /// <param name="owner">The entry or tier.</param>
    /// <param name="member">The member.</param>
    private static Record Complete(string owner, string member) => new(owner, member, null);

    /// <summary>A member realized, but incomplete.</summary>
    /// <param name="owner">The entry or tier.</param>
    /// <param name="member">The member.</param>
    /// <param name="missing">What is not realized yet.</param>
    private static Record Partial(string owner, string member, string missing) => new(owner, member, missing);
}
