import XCTest
@testable import StateUI

/// The C boundary itself: that the two sides of it name the same functions.
///
/// Nothing at run time enforces this - a renamed entry point, an export with no
/// import or an import with no export all build cleanly on both sides and fail
/// on a device, as `EntryPointNotFoundException` or a function nobody calls. So
/// it is read out of the sources here, the way `testEveryPublicApiIsDocumented`
/// reads them: a regex over source code is acceptable in a TEST, where it can
/// only under-report, and never in anything the library runs.
final class BridgeTests: XCTestCase {
    /// `Bridge/Exports.swift`, the one place `@_cdecl` is allowed.
    private func exports() throws -> String {
        try String(
            contentsOf: Fixtures.sources
                .appendingPathComponent("Bridge")
                .appendingPathComponent("Exports.swift"),
            encoding: .utf8)
    }

    /// `StateUI.Runtime/Interop/NativeMethods.cs`, the other side of it.
    private func imports() throws -> String {
        try String(
            contentsOf: Fixtures.repository
                .appendingPathComponent("src")
                .appendingPathComponent("StateUI.Runtime")
                .appendingPathComponent("Interop")
                .appendingPathComponent("NativeMethods.cs"),
            encoding: .utf8)
    }

    /// Every function exported to .NET has an import, and nothing is imported
    /// that is not exported. `stateui_app_register` is deliberately absent
    /// from both: it lives in the APP's module and its import is generated by
    /// `StateUI.targets`, because this library cannot name an application.
    func testEveryExportHasItsImportAndNothingElse() throws {
        let exported = Set(try exports().occurrences(between: "@_cdecl(\"", and: "\")"))
        let imported = Set(try imports().occurrences(between: "EntryPoint = \"", and: "\""))

        XCTAssertFalse(exported.isEmpty, "no exports found - the scan is broken")

        XCTAssertEqual(
            exported.subtracting(imported), [],
            "exported from Swift with no P/Invoke in NativeMethods.cs")

        XCTAssertEqual(
            imported.subtracting(exported), [],
            "imported in NativeMethods.cs with no @_cdecl behind it - "
                + "EntryPointNotFoundException at first call")
    }

    /// Both sides take the same number of arguments, function by function.
    ///
    /// A count is as far as text can honestly go; that the TYPES agree is the
    /// reader's job, and the two files sit side by side for exactly that. A
    /// count already catches the silent version of the failure - an argument
    /// added on one side reads garbage on the other rather than failing to
    /// bind.
    func testEveryExportAgreesWithItsImportOnArity() throws {
        func arity(of parameters: String) -> Int {
            let trimmed = parameters.trimmingCharacters(in: .whitespacesAndNewlines)
            return trimmed.isEmpty ? 0 : trimmed.filter { $0 == "," }.count + 1
        }

        // "@_cdecl("name")" ... "func x(params)" - the attribute is directly
        // above the function it exports, so the next parenthesis pair after
        // "func" is its parameter list.
        var exported: [String: Int] = [:]
        for piece in try exports().components(separatedBy: "@_cdecl(\"").dropFirst() {
            guard let name = piece.occurrences(between: "", and: "\")").first,
                let signature = piece.occurrences(between: "func ", and: ")").first,
                let open = signature.firstIndex(of: "(")
            else { continue }

            exported[name] = arity(of: String(signature[signature.index(after: open)...]))
        }

        // "EntryPoint = "name")]" ... "partial <ret> X(params);"
        var imported: [String: Int] = [:]
        for piece in try imports().components(separatedBy: "EntryPoint = \"").dropFirst() {
            guard let name = piece.occurrences(between: "", and: "\"").first,
                let declaration = piece.occurrences(between: "partial ", and: ";").first,
                let open = declaration.firstIndex(of: "("),
                let close = declaration.lastIndex(of: ")")
            else { continue }

            let inside = declaration[declaration.index(after: open)..<close]
            imported[name] = arity(of: String(inside))
        }

        for (name, count) in exported.sorted(by: { $0.key < $1.key }) {
            XCTAssertEqual(
                imported[name], count,
                "\(name) takes \(count) argument(s) in Swift and "
                    + "\(imported[name].map(String.init) ?? "none") in C#")
        }
    }

    /// Every export is spelled the way the Windows build's scan reads it.
    ///
    /// `build-windows.ps1` greps the sources for `@_cdecl("…")` to generate the
    /// `.def` export list - a spelling it does not match builds a DLL that
    /// throws `EntryPointNotFoundException` at first call, on the one platform
    /// nothing here runs on. So the exact pattern is read OUT OF the script and
    /// held against every attribute line, and a future respelling - the
    /// official `@cdecl`, say - fails here, on a Mac, naming both files.
    func testEveryExportIsSpelledTheWayTheWindowsScanReads() throws {
        let script = try String(
            contentsOf: Fixtures.repository
                .appendingPathComponent(".scripts")
                .appendingPathComponent("build-windows.ps1"),
            encoding: .utf8)

        guard let pattern = script.occurrences(between: "-Pattern '", and: "'").first else {
            return XCTFail("build-windows.ps1 no longer scans with -Pattern '…'")
        }

        let scan = try NSRegularExpression(pattern: pattern)

        for line in try exports().components(separatedBy: "\n")
        where line.contains("cdecl(\"") {
            let range = NSRange(line.startIndex..., in: line)

            XCTAssertNotNil(
                scan.firstMatch(in: line, range: range),
                "the Windows .def scan (\(pattern)) would miss: \(line.trimmingCharacters(in: .whitespaces))")
        }
    }

    /// Every `@_cdecl` in the library is in `Bridge/Exports.swift`.
    ///
    /// One file on purpose: the attribute is compiler-private, so keeping every
    /// use together makes a future migration local - and makes the surface .NET
    /// can reach auditable by reading one file.
    /// Comment lines are dropped first, the way `testTheSourcesSpellNoNames`
    /// drops them: what is forbidden is DECLARING an export outside that file,
    /// and a doc example showing an app the one line it has to write is prose.
    /// `Views/Application.swift` documents `stateUIUseApp` with exactly that
    /// example, and it belongs there.
    func testEveryExportLivesInTheBridgeFile() throws {
        for (path, text) in try Fixtures.allSources()
        where !path.hasSuffix("Bridge/Exports.swift") {
            let code = text.split(separator: "\n", omittingEmptySubsequences: false)
                .map { $0.drop(while: { $0 == " " }) }
                .filter { !$0.hasPrefix("//") }
                .joined(separator: "\n")

            XCTAssertFalse(
                code.contains("@_cdecl(\""),
                "\(path) declares an export; they all belong in Bridge/Exports.swift")
        }
    }

    /// The Windows `.def` scan drops comment lines, the way the guards do.
    ///
    /// A doc example is PROSE, and exporting a name nobody declares stops the
    /// linker dead: the library documents `stateUIUseApp` by showing an
    /// application the one line it writes - `@_cdecl("stateui_app_register")`
    /// in a `///` block in `Views/Application.swift` - and a scan that reads
    /// that puts the name in the LIBRARY's export list, where nothing defines
    /// it. `lld-link` answers `<root>: undefined symbol: stateui_app_register`
    /// and produces no DLL at all.
    ///
    /// `testEveryExportLivesInTheBridgeFile` above already calls that example
    /// prose and drops comments to allow it. This holds the SCRIPT to the same
    /// rule, and it is a test rather than a comment because the script is the
    /// half neither suite can run: nothing else here compiles for Windows.
    func testTheWindowsExportScanReadsNoProse() throws {
        let script = try String(
            contentsOf: Fixtures.repository
                .appendingPathComponent(".scripts")
                .appendingPathComponent("build-windows.ps1"),
            encoding: .utf8)

        guard let scan = script.range(of: "-Pattern '") else {
            return XCTFail("build-windows.ps1 no longer scans with -Pattern '…'")
        }

        // The filter has to come BEFORE the scan in the same pipeline; looking
        // at the whole file would pass on a comment filter used anywhere else.
        let pipeline = script[..<scan.lowerBound].suffix(400)

        XCTAssertTrue(
            pipeline.contains("StartsWith(\"//\")"),
            """
            build-windows.ps1 scans the sources for @_cdecl without dropping \
            comment lines first. The library's own doc example would then be \
            exported, no StateUI.dll would be produced, and the app would \
            run with a stale Swift side. The pipeline reads:

            \(pipeline)
            """)
    }

    /// And what the scan finds, comments dropped, is exactly what the library
    /// declares - so a stray export is caught here as well as a missing one.
    func testTheWindowsExportScanFindsExactlyWhatIsDeclared() throws {
        let declared = Set(try exports()
            .components(separatedBy: "\n")
            .filter { !$0.trimmingCharacters(in: .whitespaces).hasPrefix("//") }
            .flatMap { $0.occurrences(between: "@_cdecl(\"", and: "\"") })

        var found: Set<String> = []

        for (_, text) in try Fixtures.allSources() {
            found.formUnion(text
                .components(separatedBy: "\n")
                .filter { !$0.trimmingCharacters(in: .whitespaces).hasPrefix("//") }
                .flatMap { $0.occurrences(between: "@_cdecl(\"", and: "\"") })
        }

        XCTAssertEqual(
            found.sorted(), declared.sorted(),
            "the Windows .def would export a different set than Bridge/Exports.swift declares")
    }

    /// The environment the host pushes before the first render is readable
    /// while the tree is built - the idiom rides the device domain, and a
    /// headless test reads the defaults. The push machinery itself is
    /// HostEnvironmentTests' business; what belongs HERE is that the export
    /// exists and lands on the provider the differ seeds.
    func testTheEnvironmentTheHostPushesIsReadableAtBuildTime() {
        // Global on purpose - one environment per process - so the test puts
        // the headless default back whatever happens.
        defer {
            StandardEnvironment.device.idiom = .unknown
            Renderer.shared.clearInvalidation()
        }

        XCTAssertEqual(StandardEnvironment.device.idiom, .unknown,
                       "a headless test has no host to ask")

        var out: [UInt8] = []
        out.u8(Wire.version)
        out.u8(5)
        out.u8(7)
        for value in [
            PropValue.enumeration(DeviceIdiom.desktop.rawValue), .string("MacCatalyst"),
            .string(""), .string(""), .string(""), .string(""),
            .enumeration(DeviceType.physical.rawValue),
        ] {
            out.value(value)
        }

        let applied = out.withUnsafeBufferPointer {
            stateui_set_environment($0.baseAddress, Int32($0.count))
        }

        XCTAssertEqual(applied, 1)
        XCTAssertEqual(StandardEnvironment.device.idiom, .desktop)
    }
}

