// SPDX-FileCopyrightText: 2026 Paweł Krzywdziński and Contributors
// SPDX-License-Identifier: Apache-2.0

namespace StateUI.Maui.Protocol;

/// <summary>
/// Every property key the library's own controls carry - the MAUI property
/// name camelCased, resolved once when the session announces it.
/// </summary>
/// <remarks>
/// <para>
/// <see cref="None"/> is a key this runtime has no member for, which is what
/// every property an APPLICATION declares on its own control is. Those cannot
/// share a member - two of them on one control would collide as one
/// dictionary key and the second would overwrite the first - so they live in
/// <c>SwiftNode.OwnProps</c>, spelled, and the library's live here, numbered.
/// The split is the vocabulary's own shape: this one is closed, that one is
/// open.
/// </para>
/// <para>
/// These numbers never cross the wire; see <see cref="SwiftNodeType"/>.
/// </para>
/// </remarks>
internal enum SwiftProp : ushort
{
    /// <summary>A name this runtime has no member for.</summary>
    None = 0,

    AbsoluteLayoutBounds = 1,
    AbsoluteLayoutProportions = 2,
    Address = 3,
    AllowDrop = 6,
    PivotX = 7,
    PivotY = 8,
    Aspect = 9,
    AutomationExcludedWithChildren = 237,
    AccessibilityIdentifier = 233,
    HidesWhenInactive = 240,
    GrowsWithText = 10,
    Background = 11,
    BarBackgroundColor = 15,
    BarForegroundColor = 16,
    BorderColor = 17,
    BorderWidth = 18,
    CanDrag = 20,
    CharacterSpacing = 22,
    ShowsClearButton = 23,
    Color = 24,
    Columns = 25,
    ColumnSpacing = 26,
    Content = 27,
    IconPosition = 28,
    CornerRadius = 29,
    Count = 30,
    CurrentPage = 31,
    CursorPosition = 32,
    Data = 33,
    Date = 34,
    DragText = 36,
    Drawable = 37,
    Fill = 38,
    FillRule = 39,
    FloatsOnTop = 243,
    LayoutDirection = 45,
    FontAttributes = 47,
    FontAutoScalingEnabled = 48,
    FontFamily = 49,
    FontSize = 50,
    Format = 52,
    Frame = 75,
    GridColumn = 53,
    GridColumnSpan = 54,
    GridRow = 55,
    GridRowSpan = 56,
    Group = 57,
    GroupName = 58,
    Height = 59,
    HideSingle = 61,
    HorizontalAlignment = 63,
    HorizontalScrollBarVisibility = 64,
    HorizontalTextAlignment = 65,
    Icon = 66,
    Step = 69,
    IndicatorColor = 70,
    IndicatorSize = 71,
    IndicatorsShape = 72,
    IsAnimating = 74,
    IsOn = 77,
    ClipsContent = 78,
    IsDestructive = 79,
    IsEnabled = 80,
    IsMaximizable = 82,
    IsMinimizable = 83,
    IsOpaque = 84,
    IsOpen = 85,
    IsPassword = 86,
    IsSidebarVisible = 87,
    IsReadOnly = 88,
    IsRefreshEnabled = 89,
    IsRefreshing = 90,
    IsRunning = 91,
    IsScrollEnabled = 93,
    ShowsUserLocation = 94,
    IsSpellCheckEnabled = 95,
    IsTextPredictionEnabled = 97,
    IsTrafficEnabled = 99,
    IsVisible = 100,
    IsZoomEnabled = 101,
    Options = 103,
    InputPurpose = 105,
    Label = 106,
    LineBreak = 107,
    LineHeight = 108,
    Location = 109,
    MapType = 111,
    Margin = 112,
    Maximum = 113,
    MaximumDate = 114,
    MaximumHeight = 115,
    MaximumVisible = 118,
    MaximumWidth = 119,
    MaximumLength = 121,
    MaximumLines = 122,
    Minimum = 123,
    MinimumDate = 124,
    MinimumHeight = 125,
    MinimumWidth = 128,
    Mode = 131,
    Name = 132,
    BackButtonTitle = 133,
    HasBackButton = 134,
    HasNavigationBar = 135,
    TapCount = 138,
    Opacity = 141,
    Placement = 142,
    Orientation = 143,
    Padding = 144,
    PanTouchCount = 145,
    PanXChannel = 231,
    PanYChannel = 232,
    Placeholder = 147,
    PlaceholderColor = 148,
    Points = 149,
    Position = 150,
    Priority = 151,
    Progress = 152,
    Region = 157,
    RenderTransform = 159,
    ReturnKey = 160,
    Rotation = 161,
    RotationX = 162,
    RotationY = 163,
    Rows = 164,
    RowSpacing = 165,
    AvoidsSafeArea = 166,
    Scale = 167,
    ScaleX = 168,
    ScaleY = 169,
    ScrollOffset = 229,
    SelectedIndex = 171,
    SelectedIndicatorColor = 172,
    SelectionLength = 174,
    AccessibilityLabel = 234,
    AccessibilityHeadingLevel = 235,
    AccessibilityHint = 236,
    Side = 175,
    Source = 176,
    Spacing = 177,
    Stroke = 178,
    StrokeDashPattern = 179,
    StrokeDashOffset = 180,
    StrokeLineCap = 181,
    StrokeLineJoin = 182,
    StrokeMiterLimit = 183,
    Shape = 184,
    StrokeWidth = 185,
    Style = 186,
    Subtitle = 187,
    SwipeBehaviorOnInvoked = 188,
    SwipeDirection = 189,
    SwipeThreshold = 190,
    Text = 191,
    TextColor = 192,
    TextDecorations = 193,
    TextCase = 194,
    TextType = 195,
    Threshold = 196,
    Time = 199,
    Title = 200,
    TranslationX = 202,
    TranslationY = 203,
    Type = 204,
    UserAgent = 206,
    Value = 208,
    VerticalAlignment = 209,
    VerticalScrollBarVisibility = 210,
    VerticalTextAlignment = 211,
    Width = 212,
    WindowType = 241,
    WindowValue = 242,
    X = 215,
    X1 = 216,
    X2 = 217,
    Y = 218,
    Y1 = 219,
    Y2 = 220,
    ZIndex = 221,
    IsAccessibilityHidden = 244,
    IconSpacing = 245,
    LetsInputThrough = 246,
    IgnoresInput = 247,
    Tint = 248,
}
