// SPDX-FileCopyrightText: 2026 Paweł Krzywdziński and Contributors
// SPDX-License-Identifier: Apache-2.0

namespace StateUI.Runtime.Protocol;

/// <summary>
/// Every property key the library's own controls carry - the MAUI property
/// name camelCased, resolved once when the session announces it.
/// </summary>
/// <remarks>
/// <para>
/// <see cref="None"/> is a key this runtime has no member for, which is what
/// every property an APPLICATION declares on its own control is. Those cannot
/// share a member - two of them on one control would collide as one
/// dictionary key and the second would overwrite the first - so they live in
/// <c>SwiftNode.OwnProps</c>, spelled, and the library's live here, numbered.
/// The split is the vocabulary's own shape: this one is closed, that one is
/// open.
/// </para>
/// <para>
/// These numbers never cross the wire; see <see cref="SwiftNodeType"/>.
/// </para>
/// </remarks>
internal enum SwiftProp : ushort
{
    /// <summary>A name this runtime has no member for.</summary>
    None = 0,

    AbsoluteLayoutBounds = 1,
    AbsoluteLayoutFlags = 2,
    Address = 3,
    AlignContent = 4,
    AlignItems = 5,
    AllowDrop = 6,
    AnchorX = 7,
    AnchorY = 8,
    Aspect = 9,
    AutoSize = 10,
    Background = 11,
    BackgroundColor = 12,
    BackgroundImageSource = 13,
    BarBackground = 14,
    BarBackgroundColor = 15,
    BarTextColor = 16,
    BorderColor = 17,
    BorderWidth = 18,
    CancelButtonColor = 19,
    CanDrag = 20,
    CascadeInputTransparent = 21,
    CharacterSpacing = 22,
    ClearButtonVisibility = 23,
    Color = 24,
    ColumnDefinitions = 25,
    ColumnSpacing = 26,
    Content = 27,
    ContentLayout = 28,
    CornerRadius = 29,
    Count = 30,
    CurrentPage = 31,
    CursorPosition = 32,
    Data = 33,
    Date = 34,
    Direction = 35,
    DragText = 36,
    Drawable = 37,
    Fill = 38,
    FillRule = 39,
    FlexLayoutAlignSelf = 40,
    FlexLayoutBasis = 41,
    FlexLayoutGrow = 42,
    FlexLayoutOrder = 43,
    FlexLayoutShrink = 44,
    FlowDirection = 45,
    FlyoutLayoutBehavior = 46,
    FontAttributes = 47,
    FontAutoScalingEnabled = 48,
    FontFamily = 49,
    FontSize = 50,
    ForegroundColor = 51,
    Format = 52,
    GridColumn = 53,
    GridColumnSpan = 54,
    GridRow = 55,
    GridRowSpan = 56,
    Group = 57,
    GroupName = 58,
    Height = 59,
    HeightRequest = 60,
    HideSingle = 61,
    HideSoftInputOnTapped = 62,
    HorizontalOptions = 63,
    HorizontalScrollBarVisibility = 64,
    HorizontalTextAlignment = 65,
    Icon = 66,
    IconImageSource = 67,
    ImageSource = 68,
    Increment = 69,
    IndicatorColor = 70,
    IndicatorSize = 71,
    IndicatorsShape = 72,
    InputTransparent = 73,
    IsAnimationPlaying = 74,
    IsBusy = 76,
    IsChecked = 77,
    IsClippedToBounds = 78,
    IsDestructive = 79,
    IsEnabled = 80,
    IsGestureEnabled = 81,
    IsMaximizable = 82,
    IsMinimizable = 83,
    IsOpaque = 84,
    IsOpen = 85,
    IsPassword = 86,
    IsPresented = 87,
    IsReadOnly = 88,
    IsRefreshEnabled = 89,
    IsRefreshing = 90,
    IsRunning = 91,
    IsScrollEnabled = 93,
    IsShowingUser = 94,
    IsSpellCheckEnabled = 95,
    IsTextPredictionEnabled = 97,
    IsToggled = 98,
    IsTrafficEnabled = 99,
    IsVisible = 100,
    IsZoomEnabled = 101,
    ItemsSource = 103,
    JustifyContent = 104,
    Keyboard = 105,
    Label = 106,
    LineBreakMode = 107,
    LineHeight = 108,
    Location = 109,
    MapType = 111,
    Margin = 112,
    Maximum = 113,
    MaximumDate = 114,
    MaximumHeight = 115,
    MaximumHeightRequest = 116,
    MaximumTrackColor = 117,
    MaximumVisible = 118,
    MaximumWidth = 119,
    MaximumWidthRequest = 120,
    MaxLength = 121,
    MaxLines = 122,
    Minimum = 123,
    MinimumDate = 124,
    MinimumHeight = 125,
    MinimumHeightRequest = 126,
    MinimumTrackColor = 127,
    MinimumWidth = 128,
    MinimumWidthRequest = 129,
    ModalPresentationStyle = 130,
    Mode = 131,
    Name = 132,
    NavigationPageBackButtonTitle = 133,
    NavigationPageHasBackButton = 134,
    NavigationPageHasNavigationBar = 135,
    NavigationPageIconColor = 136,
    NavigationPageTitleIconImageSource = 137,
    NumberOfTapsRequired = 138,
    OffColor = 139,
    OnColor = 140,
    Opacity = 141,
    Order = 142,
    Orientation = 143,
    Padding = 144,
    PanTouchCount = 145,
    Placeholder = 147,
    PlaceholderColor = 148,
    Points = 149,
    Position = 150,
    Priority = 151,
    Progress = 152,
    ProgressColor = 153,
    RadiusX = 154,
    RadiusY = 155,
    RefreshColor = 156,
    Region = 157,
    RenderTransform = 159,
    ReturnType = 160,
    Rotation = 161,
    RotationX = 162,
    RotationY = 163,
    RowDefinitions = 164,
    RowSpacing = 165,
    SafeAreaEdges = 166,
    Scale = 167,
    ScaleX = 168,
    ScaleY = 169,
    ScrollMomentum = 225,
    ScrollStep = 222,
    SnapFrom = 224,
    SnapInterval = 223,
    SnapsAtMost = 226,
    SearchIconColor = 170,
    SelectedIndex = 171,
    SelectedIndicatorColor = 172,
    SelectedTabColor = 173,
    SelectionLength = 174,
    Side = 175,
    Source = 176,
    Spacing = 177,
    Stroke = 178,
    StrokeDashArray = 179,
    StrokeDashOffset = 180,
    StrokeLineCap = 181,
    StrokeLineJoin = 182,
    StrokeMiterLimit = 183,
    StrokeShape = 184,
    StrokeThickness = 185,
    Style = 186,
    Subtitle = 187,
    SwipeBehaviorOnInvoked = 188,
    SwipeDirection = 189,
    SwipeThreshold = 190,
    Text = 191,
    TextColor = 192,
    TextDecorations = 193,
    TextTransform = 194,
    TextType = 195,
    Threshold = 196,
    ThumbColor = 197,
    ThumbImageSource = 198,
    Time = 199,
    Title = 200,
    TitleColor = 201,
    TranslationX = 202,
    TranslationY = 203,
    Type = 204,
    UnselectedTabColor = 205,
    UserAgent = 206,
    UseSafeArea = 207,
    Value = 208,
    VerticalOptions = 209,
    VerticalScrollBarVisibility = 210,
    VerticalTextAlignment = 211,
    Width = 212,
    WidthRequest = 213,
    Wrap = 214,
    X = 215,
    X1 = 216,
    X2 = 217,
    Y = 218,
    Y1 = 219,
    Y2 = 220,
    ZIndex = 221,
}
