namespace StateUI.Runtime.Protocol;

/// <summary>
/// Every property key the library's own controls carry - the MAUI property
/// name camelCased, resolved once when the session announces it.
/// </summary>
/// <remarks>
/// <para>
/// <see cref="None"/> is a key this runtime has no member for, which is what
/// every property an APPLICATION declares on its own control is. Those cannot
/// share a member - two of them on one control would collide as one
/// dictionary key and the second would overwrite the first - so they live in
/// <c>SwiftNode.OwnProps</c>, spelled, and the library's live here, numbered.
/// The split is the vocabulary's own shape: this one is closed, that one is
/// open.
/// </para>
/// <para>
/// These numbers never cross the wire; see <see cref="SwiftNodeType"/>.
/// </para>
/// </remarks>
internal enum SwiftProp : ushort
{
    /// <summary>A name this runtime has no member for.</summary>
    None = 0,

    AbsoluteLayoutBounds = 1,
    AbsoluteLayoutFlags = 2,
    Address = 3,
    AlignContent = 4,
    AlignItems = 5,
    AllowDrop = 6,
    AnchorX = 7,
    AnchorY = 8,
    Aspect = 9,
    AutoSize = 10,
    Background = 11,
    BackgroundColor = 12,
    BarBackground = 13,
    BarBackgroundColor = 14,
    BarTextColor = 15,
    BorderColor = 16,
    BorderWidth = 17,
    CancelButtonColor = 18,
    CanDrag = 19,
    CascadeInputTransparent = 20,
    CharacterSpacing = 21,
    ClearButtonVisibility = 22,
    Color = 23,
    ColumnDefinitions = 24,
    ColumnSpacing = 25,
    Content = 26,
    ContentLayout = 27,
    CornerRadius = 28,
    Count = 29,
    CurrentPage = 30,
    Data = 31,
    Date = 32,
    Direction = 33,
    DragText = 34,
    Drawable = 35,
    Fill = 36,
    FillRule = 37,
    FlexLayoutAlignSelf = 38,
    FlexLayoutBasis = 39,
    FlexLayoutGrow = 40,
    FlexLayoutOrder = 41,
    FlexLayoutShrink = 42,
    FlowDirection = 43,
    FlyoutLayoutBehavior = 44,
    FontAttributes = 45,
    FontAutoScalingEnabled = 46,
    FontFamily = 47,
    FontSize = 48,
    ForegroundColor = 49,
    Format = 50,
    GridColumn = 51,
    GridColumnSpan = 52,
    GridRow = 53,
    GridRowSpan = 54,
    Group = 55,
    GroupName = 56,
    Height = 57,
    HeightRequest = 58,
    HideSingle = 59,
    HideSoftInputOnTapped = 60,
    HorizontalOptions = 61,
    HorizontalScrollBarVisibility = 62,
    HorizontalTextAlignment = 63,
    Icon = 64,
    IconImageSource = 65,
    ImageSource = 66,
    Increment = 67,
    IndicatorColor = 68,
    IndicatorSize = 69,
    IndicatorsShape = 70,
    InputTransparent = 71,
    IsBounceEnabled = 72,
    IsChecked = 73,
    IsClippedToBounds = 74,
    IsDestructive = 75,
    IsEnabled = 76,
    IsGestureEnabled = 77,
    IsOpaque = 78,
    IsOpen = 79,
    IsPassword = 80,
    IsPresented = 81,
    IsReadOnly = 82,
    IsRefreshEnabled = 83,
    IsRefreshing = 84,
    IsRunning = 85,
    IsScrollAnimated = 86,
    IsScrollEnabled = 87,
    IsShowingUser = 88,
    IsSwipeEnabled = 89,
    IsToggled = 90,
    IsTrafficEnabled = 91,
    IsVisible = 92,
    IsZoomEnabled = 93,
    ItemsLayout = 94,
    ItemsSource = 95,
    JustifyContent = 96,
    Keyboard = 97,
    Label = 98,
    LineBreakMode = 99,
    LineHeight = 100,
    Location = 101,
    Loop = 102,
    MapType = 103,
    Margin = 104,
    Maximum = 105,
    MaximumDate = 106,
    MaximumHeight = 107,
    MaximumHeightRequest = 108,
    MaximumTrackColor = 109,
    MaximumVisible = 110,
    MaximumWidth = 111,
    MaximumWidthRequest = 112,
    MaxLength = 113,
    MaxLines = 114,
    Minimum = 115,
    MinimumDate = 116,
    MinimumHeight = 117,
    MinimumHeightRequest = 118,
    MinimumTrackColor = 119,
    MinimumWidth = 120,
    MinimumWidthRequest = 121,
    ModalPresentationStyle = 122,
    Mode = 123,
    Name = 124,
    NavigationPageBackButtonTitle = 125,
    NavigationPageHasBackButton = 126,
    NavigationPageHasNavigationBar = 127,
    NavigationPageIconColor = 128,
    NavigationPageTitleIconImageSource = 129,
    NumberOfTapsRequired = 130,
    OnColor = 131,
    Opacity = 132,
    Order = 133,
    Orientation = 134,
    Padding = 135,
    PanTouchCount = 136,
    PeekAreaInsets = 137,
    Placeholder = 138,
    PlaceholderColor = 139,
    Points = 140,
    Position = 141,
    Priority = 142,
    Progress = 143,
    ProgressColor = 144,
    RadiusX = 145,
    RadiusY = 146,
    RefreshColor = 147,
    Region = 148,
    RemainingItemsThreshold = 149,
    ReturnType = 150,
    Rotation = 151,
    RotationX = 152,
    RotationY = 153,
    RowDefinitions = 154,
    RowSpacing = 155,
    SafeAreaEdges = 156,
    Scale = 157,
    ScaleX = 158,
    ScaleY = 159,
    SearchIconColor = 160,
    SelectedIndex = 161,
    SelectedIndicatorColor = 162,
    SelectedTabColor = 163,
    Side = 164,
    Source = 165,
    Spacing = 166,
    Stroke = 167,
    StrokeDashArray = 168,
    StrokeDashOffset = 169,
    StrokeLineCap = 170,
    StrokeLineJoin = 171,
    StrokeMiterLimit = 172,
    StrokeShape = 173,
    StrokeThickness = 174,
    Style = 175,
    Subtitle = 176,
    SwipeBehaviorOnInvoked = 177,
    SwipeDirection = 178,
    SwipeThreshold = 179,
    Text = 180,
    TextColor = 181,
    TextDecorations = 182,
    TextTransform = 183,
    Threshold = 184,
    ThumbColor = 185,
    ThumbImageSource = 186,
    Time = 187,
    Title = 188,
    TitleColor = 189,
    TranslationX = 190,
    TranslationY = 191,
    UnselectedTabColor = 192,
    UseSafeArea = 193,
    Value = 194,
    VerticalOptions = 195,
    VerticalScrollBarVisibility = 196,
    VerticalTextAlignment = 197,
    Width = 198,
    WidthRequest = 199,
    Wrap = 200,
    X = 201,
    X1 = 202,
    X2 = 203,
    Y = 204,
    Y1 = 205,
    Y2 = 206,
    ZIndex = 207,
}
