namespace StateUI.Runtime.Protocol;

/// <summary>
/// Every property key the library's own controls carry - the MAUI property
/// name camelCased, resolved once when the session announces it.
/// </summary>
/// <remarks>
/// <para>
/// <see cref="None"/> is a key this runtime has no member for, which is what
/// every property an APPLICATION declares on its own control is. Those cannot
/// share a member - two of them on one control would collide as one
/// dictionary key and the second would overwrite the first - so they live in
/// <c>SwiftNode.OwnProps</c>, spelled, and the library's live here, numbered.
/// The split is the vocabulary's own shape: this one is closed, that one is
/// open.
/// </para>
/// <para>
/// These numbers never cross the wire; see <see cref="SwiftNodeType"/>.
/// </para>
/// </remarks>
internal enum SwiftProp : ushort
{
    /// <summary>A name this runtime has no member for.</summary>
    None = 0,

    AbsoluteLayoutBounds = 1,
    AbsoluteLayoutFlags = 2,
    Address = 3,
    AlignContent = 4,
    AlignItems = 5,
    AllowDrop = 6,
    AnchorX = 7,
    AnchorY = 8,
    Aspect = 9,
    AutoSize = 10,
    Background = 11,
    BackgroundColor = 12,
    BarBackground = 13,
    BarBackgroundColor = 14,
    BarTextColor = 15,
    BorderColor = 16,
    BorderWidth = 17,
    CancelButtonColor = 18,
    CanDrag = 19,
    CascadeInputTransparent = 20,
    CharacterSpacing = 21,
    ClearButtonVisibility = 22,
    Color = 23,
    ColumnDefinitions = 24,
    ColumnSpacing = 25,
    Content = 26,
    ContentLayout = 27,
    CornerRadius = 28,
    Count = 29,
    CurrentPage = 30,
    Data = 31,
    Date = 32,
    Direction = 33,
    DragText = 34,
    Drawable = 35,
    Fill = 36,
    FillRule = 37,
    FlexLayoutAlignSelf = 38,
    FlexLayoutBasis = 39,
    FlexLayoutGrow = 40,
    FlexLayoutOrder = 41,
    FlexLayoutShrink = 42,
    FlowDirection = 43,
    FlyoutLayoutBehavior = 44,
    FontAttributes = 45,
    FontAutoScalingEnabled = 46,
    FontFamily = 47,
    FontSize = 48,
    ForegroundColor = 49,
    Format = 50,
    GridColumn = 51,
    GridColumnSpan = 52,
    GridRow = 53,
    GridRowSpan = 54,
    Group = 55,
    GroupName = 56,
    Height = 57,
    HeightRequest = 58,
    HideSingle = 59,
    HideSoftInputOnTapped = 60,
    HorizontalOptions = 61,
    HorizontalScrollBarVisibility = 62,
    HorizontalTextAlignment = 63,
    Icon = 64,
    IconImageSource = 65,
    ImageSource = 66,
    Increment = 67,
    IndicatorColor = 68,
    IndicatorSize = 69,
    IndicatorsShape = 70,
    InputTransparent = 71,
    IsBounceEnabled = 72,
    IsChecked = 73,
    IsClippedToBounds = 74,
    IsDestructive = 75,
    IsEnabled = 76,
    IsGestureEnabled = 77,
    IsOpaque = 78,
    IsPassword = 79,
    IsPresented = 80,
    IsReadOnly = 81,
    IsRefreshEnabled = 82,
    IsRefreshing = 83,
    IsRunning = 84,
    IsScrollAnimated = 85,
    IsScrollEnabled = 86,
    IsShowingUser = 87,
    IsSwipeEnabled = 88,
    IsToggled = 89,
    IsTrafficEnabled = 90,
    IsVisible = 91,
    IsZoomEnabled = 92,
    ItemsLayout = 93,
    ItemsSource = 94,
    JustifyContent = 95,
    Keyboard = 96,
    Label = 97,
    LineBreakMode = 98,
    LineHeight = 99,
    Location = 100,
    Loop = 101,
    MapType = 102,
    Margin = 103,
    Maximum = 104,
    MaximumDate = 105,
    MaximumHeight = 106,
    MaximumHeightRequest = 107,
    MaximumTrackColor = 108,
    MaximumVisible = 109,
    MaximumWidth = 110,
    MaximumWidthRequest = 111,
    MaxLength = 112,
    MaxLines = 113,
    Minimum = 114,
    MinimumDate = 115,
    MinimumHeight = 116,
    MinimumHeightRequest = 117,
    MinimumTrackColor = 118,
    MinimumWidth = 119,
    MinimumWidthRequest = 120,
    ModalPresentationStyle = 121,
    Mode = 122,
    Name = 123,
    NavigationPageBackButtonTitle = 124,
    NavigationPageHasBackButton = 125,
    NavigationPageHasNavigationBar = 126,
    NavigationPageIconColor = 127,
    NavigationPageTitleIconImageSource = 128,
    NumberOfTapsRequired = 129,
    OnColor = 130,
    Opacity = 131,
    Order = 132,
    Orientation = 133,
    Padding = 134,
    PanTouchCount = 135,
    PeekAreaInsets = 136,
    Placeholder = 137,
    PlaceholderColor = 138,
    Points = 139,
    Position = 140,
    Priority = 141,
    Progress = 142,
    ProgressColor = 143,
    RadiusX = 144,
    RadiusY = 145,
    RefreshColor = 146,
    Region = 147,
    ReturnType = 148,
    Rotation = 149,
    RotationX = 150,
    RotationY = 151,
    RowDefinitions = 152,
    RowSpacing = 153,
    SafeAreaEdges = 154,
    Scale = 155,
    ScaleX = 156,
    ScaleY = 157,
    SearchIconColor = 158,
    SelectedIndex = 159,
    SelectedIndicatorColor = 160,
    SelectedTabColor = 161,
    Side = 162,
    Source = 163,
    Spacing = 164,
    Stroke = 165,
    StrokeDashArray = 166,
    StrokeDashOffset = 167,
    StrokeLineCap = 168,
    StrokeLineJoin = 169,
    StrokeMiterLimit = 170,
    StrokeShape = 171,
    StrokeThickness = 172,
    Style = 173,
    Subtitle = 174,
    SwipeBehaviorOnInvoked = 175,
    SwipeDirection = 176,
    SwipeThreshold = 177,
    Text = 178,
    TextColor = 179,
    TextDecorations = 180,
    TextTransform = 181,
    Threshold = 182,
    ThumbColor = 183,
    ThumbImageSource = 184,
    Time = 185,
    Title = 186,
    TitleColor = 187,
    TranslationX = 188,
    TranslationY = 189,
    UnselectedTabColor = 190,
    UseSafeArea = 191,
    Value = 192,
    VerticalOptions = 193,
    VerticalScrollBarVisibility = 194,
    VerticalTextAlignment = 195,
    Width = 196,
    WidthRequest = 197,
    Wrap = 198,
    X = 199,
    X1 = 200,
    X2 = 201,
    Y = 202,
    Y1 = 203,
    Y2 = 204,
    ZIndex = 205,
}
